Homework003
rodkevich/go-course pull request #4
Opened 2021-07-19 12:42 UTC by rodkevich

2021-07-20 13:51 UTC, DzmitryYafremenka requested changes

2021-07-20 13:51 UTC, DzmitryYafremenka commented on homework/hw003/arrayhw/solution-hw-003-arrays.go
> +type ArrayWithFunction struct {
It's bad style to mix behavior and data.
Structure fields are for data. 
Methods are for behavior.
We can embed types that have their own methods.  But adding a function there is a very bad style.

Besides - check what will happen if you write the following code
```
	var a ArrayWithFunction
	fmt.Println(a.Avg())
```

2021-07-20 13:51 UTC, DzmitryYafremenka commented on homework/hw003/arrayhw/solution-hw-003-arrays.go
> +type Average func() float64
Why do we need this?

2021-07-20 13:51 UTC, DzmitryYafremenka commented on homework/hw003/arrayhw/solution-hw-003-arrays.go
> +func (arr *ArrayWithFunction) PrintDetailedAverageForArrImp(res float64) {
This function just "prettify value when printing". How is it connected to ArrayWithFunction type?

2021-07-20 13:51 UTC, DzmitryYafremenka commented on homework/hw003/slicehw/solution-hw-003-slices.go
> +			if len(value) < res.len {
try 从 as one of the inputs

2021-07-22 13:44 UTC, DzmitryYafremenka requested changes

2021-07-22 13:44 UTC, DzmitryYafremenka commented on cmd/hw003/solution-hw-003.go
> +	var sliceCases = []struct{ input []string }{
Why do we need struct? You only keep one type of data there( []string ) if you need array of inputs you can just use slice of []string -> [][]string.

2021-07-22 13:44 UTC, DzmitryYafremenka commented on cmd/hw003/solution-hw-003.go
> +		l, max, err := slicehw.LongestStrInSlice(each.input)
each.input - You definitely don't need structure here. You just passing one field as function arg.

2021-07-22 13:44 UTC, DzmitryYafremenka commented on homework/hw003/slicehw/solution-hw-003-slices.go
> +type results struct {
Why do we need this? We only need one string value as result.

2021-07-22 13:44 UTC, DzmitryYafremenka commented on homework/hw003/slicehw/solution-hw-003-slices.go
> +				result.list = result.list[:0]
How is this result.list works? What should it contain? And why do we need it?

2021-07-22 13:44 UTC, DzmitryYafremenka commented on homework/hw003/slicehw/solution-hw-003-slices.go
> +	for range intSlice {
Why do you mix `for  `and `for range` semantics? in this case you should use `for`.

2021-07-23 20:47 UTC, IgorZhadenovEpam commented on cmd/hw003/solution-hw-003.go
> +	"github.com/rodkevich/go-course/homework/hw003/slicehw"
Do we realy need 3 pckages? One is more than enough

2021-07-23 20:50 UTC, IgorZhadenovEpam commented on cmd/hw003/solution-hw-003.go
> +	// по заданию нужно работать с array a не slice
heh
[]float64{1, 2, 3, 4, 5, 6} - it is not an array :) 
[6]float64{1, 2, 3, 4, 5, 6} - this is an array
I can't see any array in CountAverageOfArray also
read https://blog.golang.org/slices-intro
If you need to convert array to slice:
```
var input = [6]float64{1, 2, 3, 4, 5, 6}
arr, l, avg := arrayhw.CountAverageOfArray(input[:])
```

2021-07-23 21:02 UTC, IgorZhadenovEpam commented on cmd/hw003/solution-hw-003.go
> +	arr, l, avg := arrayhw.CountAverageOfArray(input)
It is nice that you know about multiple return values but we need just one (average). Don't overcomplicate your code unnecessarily

2021-07-23 21:21 UTC, IgorZhadenovEpam commented on homework/hw003/slicehw/solution-hw-003-slices.go
> +func LongestStrInSlice(sliceOfStrings []string) (length int, s string, err error) {
You are playing with code but result is unreadable and overcomplicated. Is it possible to get the longest word using 5-7 lines of code?

2021-07-27 19:40 UTC, rodkevich commented on homework/hw003/arrayhw/solution-hw-003-arrays.go
> +type Input = [6]float64
done

2021-07-27 19:52 UTC, IgorZhadenovEpam approved these changes

2021-07-28 08:38 UTC, rodkevich commented on cmd/hw003/solution-hw-003.go
> +		Avg: func() float64 {
fixed

2021-07-28 08:39 UTC, merged